### ISSUE TITLE
РЕЗОВ НЕ РАБОТАЕТ

### ISSUE THREAD

**Issue by gentoocat** [Nediorg/reZov#1]
ЛОГИ : ИДИ В ПЕНЬ
STACKTRACE : ИДИ В ПЕНЬ

ПОЧИНИ ЧТОБ РАБОТАЛО

**Comment by Nediorg** [comment]
все работает ты врешь

**Comment by gentoocat** [comment]
не работает

**Comment by Nediorg** [comment]
да иди нафик
